### ISSUE TITLE
Could not determine kind of name for C.fmpz_factor_pp1

### ISSUE THREAD

**Issue by StarHack** [sourcekris/goRsaTool#9]
I tried to set up this project under macOS but I get the following error message at the last step:

```
go build
# github.com/sourcekris/goflint
../go/pkg/mod/github.com/sourcekris/goflint@v1.0.0/flint.go:1044:13: could not determine kind of name for C.fmpz_factor_pp1
make: *** [build] Error 1
```

The FLINT2 and GMP-ECM dependencies have already been installed in advance, as instructed.

**Comment by meme-lord** [comment]
Getting same error on Arch

**Comment by Arul-Sujith** [comment]
Same error on kali 2024.1

**Comment by sourcekris** [comment]
Thanks, this is likely an issue with the upstream libflint library changing the API which is similar to something that happened in the past (https://github.com/sourcekris/goRsaTool/issues/3). I'll figure out a workaround to get it building again.

**Comment by sourcekris** [comment]
Fixed in https://github.com/sourcekris/goRsaTool/commit/ccc723d465a8de82d298ae8e2941d376cf5290e3
